name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger webhook
        run: |
          curl -X POST https://webhook.frederikbarbre.dk/portfolio-webhook \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
          --data '{"ref": "${{ github.ref }}", "repository": "${{ github.repository }}", "pusher": "${{ github.actor }}"}'
